[toolchain]
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.17.28" # Solana version to use

[features]
seeds = true
skip-lint = false

[programs.localnet]
fjord_lbp = "fjorR4ubuG42xkRUF6SrA1hKkb1T4LqgfupE1mPLK4K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# Originally: wallet = "/Users/<USER>/.config/solana/id.json"
wallet = "./deployment-keypair/id.json" # Path to the wallet keypair to use for deployments/upgrades

[workspace]
types = "types"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
