# A github action that generates the typechain-types
# handy to keep it out of human managed source control
# author: Ben Hooper (benhooper.eth)
name: Generate Typechain Types and Chuck em in Source Control

# run when manually triggered, or when packages/contracts/contracts
# is modified

# this will run when the PR is closed, modifying the typechain-types
# folder in source control (hopefully) before this folder is used
# in other apps/services (mainly vercel).
on:
  pull_request:
    paths:
      - "packages/contracts/contracts"
    types:
      - closed
  workflow_dispatch:

# run all commands
jobs:
  generate_typechain_types_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # this may need to change?

      # as the name implies
      - name: Install hardhat and run typechain command
        run: |
          # installation commands
          cd packages/contracts
          yarn install
          yarn hardhat typechain

          # add typechain-types to source control
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -f typechain-types # -f cause typechain-types is in .gitignore
          git commit -m "chore: 🤖 updated typechain-types"

      # pushes to the repo as github actions user
      - name: Push typechain-types to source control
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
